name: Github Pages Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@latest

      - name: Install and build
        working-directory: ./ghactions-test
        run: npm i && npm run build:github && cp dist/ghactions-test/index.html dist/ghactions-test/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ghactions-test/dist/ghactions-test
